apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-ms
  labels:
    app: hello-world-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-ms
  template:
    metadata:
      labels:
        app: hello-world-ms
    spec:
      containers:
      - name: hello-world-ms-container
        image: ghcr.io/parthibhalder21/devsecops-hello-world:__IMAGE_TAG__
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
