apiVersion: v1
kind: Service
metadata:
  name: hello-world-ms-service
  labels:
    app: hello-world-ms
  annotations:
    prometheus.io/scrape: 'true' 
    prometheus.io/port: '8080'
    prometheus.io/path: '/metrics'
spec:
  type: LoadBalancer 
  selector:
    app: hello-world-ms
  ports:
  - name: http-app
    port: 80 
    targetPort: 8080
